* Summer 2015 summary

* Todo [1/4]
  - [ ] BLM 
    - [X] Talk to Iacopo and set up a meeting, he`s back on 2015-07-06 
    - [X] Set up meeting with Iacopo and Ewald 
    - [ ] Decide on data analysis needed, software, work to be done, contacts
    - [ ] Meeting agenda:
      - Does the BLM output correct data?
      - Can this data be used now in CHARM?
      - Where is the data logged?
      - Are there any known issues with the BLM, is the timing correct?
      - Who do we contact if there are problems with the BLM?
    - [ ] Set up LaTeX template for minutes
    - [ ] Write meeting minutes
    - Reference [[http://cds.cern.ch/record/1144077/files/CERN-THESIS-2008-099.pdf][Beam loss calibration studies for high energy proton accelerators]]
  - [ ] BPM/silicon ddetector and grid type detector
    - [X] Read PhD from Salvatore
    - [ ] Find info on work done, short summary on each {{Summary of previous theoretical work done}}
      - [[http://scitation.aip.org/docserver/fulltext/aapm/journal/medphys/30/8/1.1591431.pdf?expires=1435910067&id=id&accname=2098973&checksum=17174028E8F9D680C74C6473D041FB74][Diamond detector versus silicon diode and ion chamber in photon beams of different energy and field size]]
      - [[http://ac.els-cdn.com/S0168900204001512/1-s2.0-S0168900204001512-main.pdf?_tid=5f45ff82-2162-11e5-9161-00000aab0f26&acdnat=1435914389_8f888ad62741ec329e04e33444fbbdf6][Measurement of the n-TOF beam profile with a micromegas detector]]
      - [[https://cds.cern.ch/record/2025856/files/jinst14_01_c01058.pdf][Applications of triple GEM detectors beyond particle and nuclear physics]]
      - [[https://cds.cern.ch/record/2025856/files/jinst14_01_c01058.pdf][Measuring radiation environment in LHC or anywhere else, on your computer screen with Medipix]]
      - The new version of Radiation Monitor system for the electronics at CERN [S. Danzeca].
    - [ ] Summary of findings
  - [X] Ask Maurice if its possible to get info from his server for BPM
  - [ ] Poster for CHARM
    - [X] Feasibility check in LaTeX
    - [ ] Outline for the two posters 
      - [X] First poster overview
      - [ ] Second Poster with different Detectors overview
    - [ ] Create two poster mock ups in latex
      - [X] First poster with overview mock up
      - [ ] Second Poster with different Detectors mock up

* Summary of previous theoretical work done
** (RadMon) The new version of Radiation Monitor system for the electronics at CERN. ref: S. Danzeca
*** RadFet
  - Total Ionizing Dose with RadFet
  - 100 nm higher TID range
  - 400 nm higher resolution
  - changing of the bias voltage leads to changes in threshold voltage, change is not linear with TID, calibration is needed
  - relation between drain current and drain-source potential is used to measure variation of threshold voltage at different doses
  - 100nm linear fit valid up to 100 Gy, 400nm fit valid up to 100 Gy, above that power fit
*** SRAM
  - High Energy Hadron and Thermal neutron fluence with SRAM
  - Flipped bits are counted, knowing the cross section count the number of particles that hit the device
*** FGDOS (Floating Gate Dosimeter) 
  - Advantages over regular MOS transistor: mechanism of measurement is the transport of electrons in the floating gate, which is faster than transport of holes and not affected by the trapping in the oxide to the same degree
  - The mechanism is the annihilation of the stored charges in the floating gate due to the radiation induced charges in the oxide surrounding the floating gate
  - When the floating gate is discharging the threshold voltage in the reading MOSFET is changed
  - In the FGDOS sensor the variation of the threshold is converted into a frequency shift by an embedded oscillator in the IC
  - suffers less from annealing effect than RadFet, at lower TID
** Applications of triple GEM detectors beyond particle and nuclear physics
  - Micro-Pattern Gaseous Detectors (MPGD) have opened the way for the construction of detectors whose performance surpasses that of the previous generations in terms of spatial resolution, high-rate capability and increased radiation hardness. Led by the Micro-Mesh Gaseous Structure (Micromegas) and the Gas Electron Multiplier (GEM), some MPGDs are mature technologies used in a variety of experiments at high energy physics. What we report in this article is the experience explored in the last years with a compact GEM detector system in several applications as medical imaging, dosimetry and beam diagnostics for high energy beams and for nuclear reactors. For sake of shortness, only performance on soft X-ray and neutron detection will be described in detail. Also a description of the new promising highly pixelated GEM detector will be presented (MediPix)
**  Medipix
  - Medipix is a CMOS pixel detector readout chip designed to be connected to a segmented semiconductor sensor.
  - With the Medipix family of radiation imaging detectors one can measure dose and dose rate over a dynamic range of 10^14 with a single device, starting from extremely low intensities, far below dangerous levels.
  - The radiation is sampled by the 2cm^2 sensor with accurately adjustable exposure times.
** Diamond detector versus silicon diode and ion chamber in photon beams of different energy and field size
*** Advantages of a diamond detector
- the high sensitivity of diamond material permits to build small size dosimeters suitable  for accurate  determination  of  output  factors,  percent depth dose and transverse profiles, also when field sizes are small,  which  is  the  condition  where  ion  chambers  do  not have an appropriate spatial resolution
- Its features compare favorably with those of ion chamber and silicon diode systems. Its tissue equivalence  does  not  introduce  an  energy  dependence  effect  in  the  response, which, on the contrary, can be present in silicon diodes.
*** Drawbacks to be considered in the use of the diamond detector
- signal shows a dose rate dependence that must be accounted for in order  to  obtain  correct  dose  distributions,  while  the  results here  reported  exclude  such  dependence  for  silicon
- it  is less user friendly, since it necessitates a pre-irradiation dose, before daily use, to stabilize the response
- it has a slow  response  in  time,  needing  up  to  about 2 s to obtain signal  stability, 

**  