Summer 2015 summary

* Todo [0/4]
  - [ ] BLM 
    - [X] Talk to Iacopo and set up a meeting, he`s back on 2015-07-06 
    - [ ] Set up meeting with Julien, Iacopo and Christos
    - [ ] Decide on data analysis needed, software
  - [ ] BPM/silicon ddetector and grid type detector
    - [X] Read PhD from Salvatore
    - [ ] Find info on work done, short summary on each {{Summary of previous theoretical work done}}
      - [[http://scitation.aip.org/docserver/fulltext/aapm/journal/medphys/30/8/1.1591431.pdf?expires=1435910067&id=id&accname=2098973&checksum=17174028E8F9D680C74C6473D041FB74][Diamond detector versus silicon diode and ion chamber in photon beams of different energy and field size]]
      - [[http://ac.els-cdn.com/S0168900204001512/1-s2.0-S0168900204001512-main.pdf?_tid=5f45ff82-2162-11e5-9161-00000aab0f26&acdnat=1435914389_8f888ad62741ec329e04e33444fbbdf6][Measurement of the n-TOF beam profile with a micromegas detector]]
      - The new version of Radiation Monitor system for the electronics at CERN.
    - [ ] Summary of findings to Julien
    - [ ] More info from Publications
  - [ ] Ask Maurice if its possible to get info from his server for BPM
  - [ ] Poster for CHARM
    - [X] Feasibility check in LaTeX
    - [ ] Outline for the two posters 
    - [ ] Create two poster mockups in latex

* Summary of previous theoretical work done

**  (RadMon) The new version of Radiation Monitor system for the electronics at CERN.
*** RadFet
  - Total Ionizing Dose with RadFet
  - 100 nm higher TID range
  - 400 nm higher resolution
*** SRAM
  - Fluence with SRAM

**  Measurement of the n-TOF beam profile with a micromegas detector
*** 

** Diamond detector versus silicon diode and ion chamber in photon beams of different energy and field size

*** Advantages of a diamond detector
  - the high sensitivity of diamond material permits to build small size dosimeters suitable  for accurate  determination  of  output  factors,  percent depth dose and transverse profiles, also when field sizes are small,  which  is  the  condition  where  ion  chambers  do  not have an appropriate spatial resolution
 - Its features compare favorably with those of ion chamber and silicon diode systems. Its tissue equivalence  does  not  introduce  an  energy  dependence  effect  in  the  response, which, on the contrary, can be present in silicon diodes.

*** Drawbacks to be considered in the use of the diamond detector
- signal shows a dose rate dependence that must be accounted for in order  to  obtain  correct  dose  distributions,  while  the  results here  reported  exclude  such  dependence  for  silicon
- it  is less user friendly, since it necessitates a pre-irradiation dose, before daily use, to stabilize the response
- it has a slow  response  in  time,  needing  up  to  about 2 s to obtain signal  stability, 

**  